
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"   # Hi
    networks:
      - my-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"     # Host port 6379 maps to Redis default 6379
    networks:
      - my-network
    volumes:
      - redis-data:/data

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"    # Access mongo-express UI on localhost:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false
    networks:
      - my-network

  quizapp:
    container_name: quizapp
    build:
      context: .
      dockerfile: DockerFile
    image: quizapp
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - redis
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
