name: Build and Push Docker Image

on:
  push:
    branches:
      - git_action
    paths:
      - 'Dockerfile'
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}  # MUST use secrets
        password: ${{ secrets.DOCKER_HUB_TOKEN }}    # NEVER hardcode

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          yourname/quizapp:latest
          yourname/quizapp:${{ github.sha }}
          yourname/quizapp:run-${{ github.run_number }}
