name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - git_action
    paths:
      - 'Dockerfile'
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6  # ⬅️ Use correct version (latest is v6)
        with:
          image: zangetsu203/quizapp
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest,${{ github.sha }},run-${{ github.run_number }}  # ⬅️ Must be `tags` not `
